### ISSUE TITLE
Typo in docker compose section README

### ISSUE THREAD

**Issue by sergey-koba-mobidev** [manticoresoftware/docker#18]
```
volumes:
      - ./data:/var/lib/manticore
```
Should be
```
volumes:
      - ./data:/var/lib/manticore/data
```

**Comment by dzek69** [comment]
This is probably outdated issue?

I have two instances of Manticore right now, 5.x and 6.x

For both this is what I noticed:
- each table has its own directory in `/var/lib/manticore`, not inside `/var/lib/manticore/data`
- there is a `binlog` dir there too

But I don't have `data` dir.

All these seems worthy having as a mounted volume, so I believe something has changed since 5.0 (5.0 was released 2 months after this issue was opened).

So I believe this issue can be closed.

**Comment by sanikolaev** [comment]
> So I believe this issue can be closed

So do I. `/var/lib/manticore/data` is a dir which Manticore Search packages still create (even in the latest release), but it's never used then until you change the `data_dir` to it explicitly. We have in plans to remove it.

So I'm closing this issue. Feel free to reopen if there's still any issue with it.
