### ISSUE TITLE
Plain index creation on docker container startup

### ISSUE THREAD

**Issue by pwoszczyk** [manticoresoftware/docker#35]
Is any way to create and fulfill a plain index on Docker container startup?   
  
I have a limited data set (a few million) that can be loaded in seconds. I don't plan to use volumes.  
  
My config:  
```  
source my_database  
{  
    type = mysql  
    sql_host = db  
    sql_user = root  
    sql_pass = pass  
    sql_db = database  
    sql_port = 3306  
  
    sql_query_pre = SET CHARACTER_SET_RESULTS=utf8  
    sql_query_pre = SET NAMES utf8  
    sql_query = SELECT id, text FROM table  
}  
  
index my_index  
{  
    type = plain  
    source = my_database  
    path = /var/lib/manticore/data/my_index  
}  
```  
  
The container starts with warnings:  
```  
[Mon Jul 17 15:27:53.004 2023] [98] WARNING: Unable to load header... Error failed to open /var/lib/manticore/data/my_index.sph: No such file or directory  
[Mon Jul 17 15:27:53.004 2023] [98] WARNING: table 'my_index': prealloc: failed to open /var/lib/manticore/data/my_index.sph: No such file or directory - NOT SERVING  
```  
  
I can perform indexer   RELOAD TABLES after startup but want to avoid it.  
  
I don't want to overwrite ENTRYPOINT because the current implementation support the Manticore Buddy installation. Future support will be hard if I copy & extend the current entrypoint.  
  
Is any way? Did I miss some config witch enables plain index creation after startup?

**Comment by sanikolaev** [comment]
Provided these 3 things:

> on Docker container startup?

>  I don't plan to use volumes.

> I don't want to overwrite ENTRYPOINT

I think the only way to go is a wrapper script which starts up the container and once it's started, runs indexing and executes RELOAD, but since you said:

> I can perform indexer + RELOAD TABLES after startup but want to avoid it.

I'm afraid there's no way at all, you have to weaken the requirements. 

There's no functionality in Manticore to run indexing automatically on searchd start. I think it would make sense to modify the entrypoint, so it can do it. Feel free to make a pull request if you decide to go this way.

**Comment by pwoszczyk** [comment]
Thank you for your response.
